export const title = {
    mintSuccess: "발행 성공",
    mintFail: "발행 실패",
    saveSuccess: "성공적으로 보관되었습니다.",
    saveFail: "보관에 실패하였습니다.",
    sellRegisteSuccess: "판매등록 성공",
    sellRegisteFail: "판매등록 실패",
    boughtSuccess: "구매 성공",
    boughtFail: "구매 실패",
    SaleListComplete: "판매완료",

    ////// History Page ///////
    boughtTitle: "구매",
    soldTitle: "판매",
    mintedTitle: "생성",

    ///// Home Page ////////
    NFTName: "NFT 이름",
    TradingPrice: "거래 가격",
    RegisterSalesTime: "판매 등록시각",
    All: "전체",
    Image: "이미지",
    Video: "동영상",
    Loginisnecessary: "로그인이 필요합니다.",
    Login: "로그인",

    ///// Login Page ////////
    Pleaseselectonemethodtologin: "아래 방법 중 한가지를 선택하여 로그인 해주세요.",
    Loginbykaikas: "Kaikas로 로그인하기",
    Loginbymetamask: "Metamask로 로그인하기",

    ///// Wallet Info ///////
    content: "콘텐츠",
    category: "카테고리",
    NFTID: "NFT ID",
    NFTName: "NFT 이름",
    MintTime: "발행 시각",
    MintStatus: "발행 상태",
    Edit: "수정",
    Sale: "판매",
    RegisterationTime: "등록 시각",
    SalePrice: "판매가격",
    BuyPrice: "구매가격",
    BuyCompletionTime: "구매 완료시각",
    TxID: "TxID",
    Type: "유형",
    PriceTrading: "거래 가격",
    TradingCompletionTime: "거래 완료시각",
    View: "보기",
    NFTMintList: "NFT 발행목록",
    NFTSalesList: "NFT 판매목록",
    NFTBuyCompletion: "NFT 구매완료",
    NFTHistory: "NFT 히스토리",
    NFTIDORNameSearch: "NFT ID 또는 이름 검색",
    RegisterDate: "가입일",
    Address: "지갑주소",
    Balance: "잔고",
    Kaikas: "KAIKAS",
    Metamask: "METAMASK",
    Close: "닫기",
    OwnerAddress: "소유자 지갑주소",
    Status: "상태",
    Description: "설명",
    Stop: "중지",
    MySalePrice: "나의 판매 가격",
    MyBuyingPrice: "나의 구매 가격",
    MyTradingPrice: "나의 거래 가격",
    History: "히스토리",
    Buyer: "구매자",
    Seller: "판매자",
    SaleCompleteTime: "판매 완료시각",
    EditNFT: "NFT 수정하기",
    ImpossibleToEditContent: "콘텐츠 수정은 불가능합니다.",
    Name: "이름",
    SellNFT: "NFT 판매하기",
    Register: "판매", // For sale NFT
    CreationDate: "발행 시각",
    Listing: "목록 로딩중",
    Update: "수정",
    SaleUpdateNFT: "NFT 판매수정",
    NFTDetailInfo: "NFT 상세정보",
    EscareNFTMarketplace: "ESCARE NFT 마켓플레이스",
    Youcanhavemany: "다양한 NFT 경험을 해보세요",
    SearchByName: "NFT 이름으로 검색해보세요",
    Buy: "구매",
    BuyingPrice: "구매가격",
    BuyTheNFT: "해당 NFT를 구매합니다.",
    Buying: "구매중",
    MintNFT: "NFT 발행하기",
    Mint: "발행",
    UploadFileType: "업로드 가능한 파일 형태 : JPG, PNG, MP4, 최대 크기: 50MB!",
    UploadVideoORImage: "이미지 또는 동영상을 업로드해주세요.",
    Minting: "발행중",
    PageNotFound: "페이지를 찾을수 없습니다.",
    PageNotFoundTitle: "지금 찾고있는 페이지가 존재하지 않습니다.",
    Home: "Home!",
    ContactUs: "Contact Us!",
    Somethingwentwrong: "도중에 오류가 발행하였습니다.",
    PleaseTryAgain: "후에 다시 시도해주세요.",
    PleaseLoginFirst: "먼저 로그인을 해주세요.",

    /// Mobile Page //////
    WillYouBuy: "구매하시겠습니까?",
    PleaseSelectOneWallet: "아래 방법 중 한가지를 선택하여 로그인 해주세요.",

    /// Menu //
    Logout: "로그아웃",
    NFTMint: "NFT 발행",
    NFTBuy: "NFT 구매",
    WalletInfo: "지갑정보",
    NFTSalesRegister: "NFT 판매등록",

    //footer
    MarketPlace: "마켓플레이스",
    MarketPlaceDescription: "다양한 NFT를 만나보세요.",
    Representative: "대표이사",
    RepresentativeName: "정경원",
    BusinessNumber: "사업자등록번호",
    FooterAddress: "주소",
    FooterAddressDetail: "서울시 영동포구국제금융로6길 33",

    //////// title ////////
    loginTitle: "ESCARE | 로그인",
    WalletInfotitle: "ESCARE | 지갑정보",
    NFTMintTitle: "ESCARE | NFT 발행",
    NFTBuyTitle: "ESCARE | NFT 구매"

}