export const title = {
    mintSuccess: "Mint Success",
    mintFail: "Mint Failed",
    saveSuccess: "Save Success",
    saveFail: "Save Failed",
    sellRegisteSuccess: "Sell Registe Success",
    sellRegisteFail: "Sell Registe Failed",
    sellStopSuccess: "Sell Stop Success",////////// 6-10 added
    sellStopFail: "Sell Stop Failed",////////// 6-10 added
    boughtSuccess: "Buy Success",
    boughtFail: "Buy Fail",
    SaleListComplete: "Complete",

    ////// History Page ///////
    boughtTitle: "Buy",
    soldTitle: "Sell",
    mintedTitle: "Creation",

    ///// Home Page ////////
    NFTName: "NFT Name!",
    TradingPrice: "TradingPrice!",
    RegisterSalesTime: "RegisterSalesTime!",
    All: "All!",
    Image: "Image!",
    Video: "Video!",
    Loginisnecessary: "Loginisnecessary!",
    Login: "Login!",

    ///// Login Page ////////
    Pleaseselectonemethodtologin: "Pleaseselectonemethodtologin!",
    Loginbykaikas: "Loginbykaikas!",
    Loginbymetamask: "Loginbymetamask!",

    ///// Wallet Info ///////
    content: "content!",
    category: "category!",
    NFTID: "NFTID!",
    NFTName: "NFTName!",
    MintTime: "MintTime!",
    MintStatus: "MintStatus!",
    Edit: "edit!",
    Sale: "sale!",
    RegisterationTime: "RegisterationTime!",
    SalePrice: "SalePrice!",
    BuyPrice: "buyPrice!",
    BuyCompletionTime: "buyCompletionTime!",
    TxID: "TxID!",
    Type: "Type!",
    PriceTrading: "PriceTrading!",
    TradingCompletionTime: "TradingCompletionTime!",
    View: "View!",
    NFTMintList: "NFTMintList!",
    NFTSalesList: "NFTSalesList!",
    NFTBuyCompletion: "NFTBuyCompletion!",
    NFTHistory: "NFTHistory!",
    NFTIDORNameSearch: "NFTIDORNameSearch!",
    RegisterDate: "RegisterDate!",
    Address: "Address!",
    Balance: "Balance!",
    Kaikas: "Kaikas!",
    Metamask: "Metamask!",
    Close: "Close!",
    OwnerAddress: "OwnerAddress!",
    Status: "Status!",
    Description: "Description!",
    Stop: "Stop!",
    MySalePrice: "MySalePrice!",
    MyBuyingPrice: "MyBuyingPrice!",
    MyTradingPrice: "MyTradingPrice!",
    History: "History!",
    Buyer: "Buyer!",
    Seller: "Seller!",
    SaleCompleteTime: "SaleCompleteTime!",
    EditNFT: "EditNFT!",
    ImpossibleToEditContent: "ImpossibleToEditContent!",
    Name: "Name!",
    SellNFT: "SellNFT!",
    Register: "Register!",
    CreationDate: "CreationDate!",
    Listing: "Listing...!",
    Update: "Update!",
    SaleUpdateNFT: "SaleUpdateNFT!",
    NFTDetailInfo: "NFTDetailInfo!",
    EscareNFTMarketplace: "EscareNFTMarketplace!",
    Youcanhavemany: "You can have many experiences in NFTs.!",
    SearchByName: "SearchByName!",
    Buy: "Buy!",
    BuyingPrice: "BuyingPrice!",
    BuyTheNFT: "BuyTheNFT!",
    Buying: "Buying...!",
    SellStopping: "SellStop...!", ////////// 6-10 added
    MintNFT: "MintNFT!",
    Mint: "Mint!",
    UploadFileType: "upload file format : JPG, PNG, MP4, max size: 50MB!",
    UploadVideoORImage: "UploadVideoORImage!",
    Minting: "Minting...!",
    PageNotFound: "oops! Page not found!",
    PageNotFoundTitle: "Oops! The page you are looking for does not exist. It might have been moved or deleted.!",
    Home: "Home!",
    ContactUs: "ContactUs!",
    Somethingwentwrong: "Somethingwentwrong!",
    PleaseTryAgain: "Please try again!!",
    PleaseLoginFirst: "PleaseLoginFirst!",

    /// Mobile Page //////
    WillYouBuy: "Will you Buy?!",
    PleaseSelectOneWallet: "Please select one Wallet to login!",

    /// Menu //
    Logout: "Logout!",
    NFTMint: "NFTMint!",
    NFTBuy: "NFTBuy!",
    WalletInfo: "WalletInfo!",

    NFTSalesRegister: "Register NFT Sales",
    MarketPlace: "Marketplace",
    MarketPlaceDescription: "Meet various NFTs",
    Representative: "Representative",
    RepresentativeName: "James",
    BusinessNumber: "Business Number",
    FooterAddress: "Address",
    FooterAddressDetail: "Ueyq akuseraw erqiuwr qwieu",

    //////// title ////////
    loginTitle: "ESCARE | Login",
    WalletInfotitle: "ESCARE | WalletInfo",
    NFTMintTitle: "ESCARE | NFT Mint",
    NFTBuyTitle: "ESCARE | NFT Buy"
}